name: ciarlare develop

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-14 ]

    steps:
      - uses: actions/checkout@v4
      - name: print ls
        run: ls
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install test dependencies
        run: python -m pip install -r requirements-test.txt
      - name: Install ciarlare
        run: python setup.py install
      - name: run pytest
        run: python -m pytest ciarlare
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ciarlare
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      # retrieve your distributions here
      - name: print ls
        run: ls .git
      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install build
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            repository-url: https://test.pypi.org/legacy/
            password: ${{ secrets.PYPI_TEST_TOKEN }}

